### ISSUE TITLE
it seem to  work again in Xcode 8.1 ! please update Xcode 8.1 uuid

### ISSUE THREAD

**Issue by tanpengsccd** [ksuther/KSImageNamed-Xcode#89]
thanks！！！

**Comment by AMEstudio** [comment]
if your xcode is xcode8.1 or 8.1+
you must add your xcode's uuid to the KSImage's project so that the KSImageNamed can work

the way to add uuid is:
find a plist file in KSImageNamed's project which is named 'KSImageNamed-Info.plist'
add your xcode's uuid to array 'DVTPlugInCompatibilityUUIDs' and then run the project

BTW the xcode8.1's uuid is
DA4FDFD8-C509-4D8B-8B55-84A7B66AE701
